---
- name: install deps
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name: ca-certificates
- name: fetch gitlab installer
  get_url:
    url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.deb.sh
    dest: /tmp/gitlab.sh
    mode: 1770
- name: setup gitlab
  shell: "/tmp/gitlab.sh"
- name: install gitlab
  apt:
    name: gitlab-ee
- name: enable lets encrypt
  blockinfile:
    path: /etc/gitlab/gitlab.rb
    block: |
      letsencrypt['enable'] = true
- name: reconfigure gitlab
  shell: gitlab-ctl reconfigure
