---
- name: setup grafana on arm
  include: setup_arm.yml
  when: ansible_architecture == "armv7l"
- name: setup grafana on x86_64
  include: setup_x86.yml
  when: ansible_architecture == "x86_64"
- name: Start service grafana, if not running
  service:
    name: grafana-server
    state: started
