version: '3'
services:
  grafana:
    image: "fg2it/grafana-armhf:v5.1.3"
    ports:
      - "3000:3000"
    volumes:
      - /mnt/gluster/home/grafana/etc:/etc/grafana
      - /mnt/gluster/home/grafana/var:/var/lib/grafana
  influxdb:
    image: "influxdb"
    ports:
      - "8086:8086"
    volumes:
      - /mnt/gluster/home/influxdb/var:/var/lib/influxdb
  # snips:
  #   # https://github.com/snipsco/snips-platform-documentation/wiki/6.--Miscellaneous#using-docker
  #   image: "snipsdocker/platform"
  #   # privileged: true
  #   ports:
  #     - "9898:1883"
  #   volumes:
  #     - /home/pi/.asoundrc:/root/.asoundrc
  #     - /dev/snd:/dev/snd
  #     - /mnt/gluster/home/snips/config/assistant:/usr/share/snips/assistant
  registry:
    image: " budry/registry-arm:latest"
    ports:
      - "5000:5000"
