version: '3'
services:
  grafana:
    image: "fg2it/grafana-armhf:v5.1.3"
    user: pi
    ports:
      - "3000:3000"
    volumes:
      - /mnt/gluster/home/grafana/etc:/etc/grafana
      - /mnt/gluster/home/grafana/var:/var/lib/grafana
  influxdb:
    image: "influxdb"
    ports:
      - "8086:8086"
    volumes:
      - /mnt/gluster/home/influxdb/var:/var/lib/influxdb
