# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "snips" do |box|
    box.vm.hostname = 'snips'
    box.ssh.username = 'root'
    box.ssh.private_key_path = '~/.ssh/id_rsa'

    # box.vm.network "forwarded_port", guest: 8086, host: 8086

    # box.vm.synced_folder '/mnt/gluster/home/influxdb/var/', '/var/lib/influxdb/', user: 107, group: 65534

    box.vm.provider :docker do |d|
      d.build_dir = "../../docker"
      d.remains_running = true
      d.has_ssh = true
    end

    box.vm.provision :ansible do |ansible|
      ansible.config_file = "../../ansible.cfg"
      ansible.playbook = "playbook.yml"
    end

  end
end
