---
- name: install package
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name: openvpn
- name: fetch node setup
  get_url:
    url: https://deb.nodesource.com/setup_10.x
    dest: /tmp/node-setup.sh
    mode: 1770
- name: run setup script
  tags:
  - setup
  shell: "/tmp/node-setup.sh"
  register: node_setup
- name: install nodejs
  apt: name={{item}} state=present
  with_items:
    - nodejs
    - build-essential
