# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "grafana" do |box|
    box.vm.hostname = "grafana"
    box.vm.box = "/mnt/gluster/box/vagrant-lxc-stretch-armhf.box"

    box.vm.network "forwarded_port", guest: 3000, host: 3000

    box.vm.synced_folder '/mnt/gluster/home/grafana/etc/', '/etc/grafana/'
    box.vm.synced_folder '/mnt/gluster/home/grafana/var/', '/var/lib/grafana/', user: 472, group: 472

    box.vm.provider :lxc do |lxc|
      lxc.backingstore = 'dir'
      lxc.backingstore_option '--dir', '/mnt/gluster/lxc/grafana'
      lxc.customize 'aa_allow_incomplete', '1'
    end

    box.vm.provision :ansible do |ansible|
      ansible.config_file = "../../ansible.cfg"
      ansible.playbook = "playbook.yml"
    end

  end
  config.vm.define "influxdb" do |box|
    box.vm.hostname = 'influxdb'
    box.vm.box = "/mnt/gluster/box/vagrant-lxc-stretch-armhf.box"

    box.vm.network "forwarded_port", guest: 8086, host: 8086

    box.vm.synced_folder '/mnt/gluster/home/influxdb/var/', '/var/lib/influxdb/', user: 107, group: 65534

    box.vm.provider :lxc do |lxc|
      lxc.backingstore = 'dir'
      # lxc.backingstore_option '--dir', '/mnt/gluster/lxc/influxdb'
      # lxc.customize 'aa_allow_incomplete', '1'
    end

    box.vm.provision :ansible do |ansible|
      ansible.config_file = "../../ansible.cfg"
      ansible.playbook = "playbook.yml"
    end

  end
end
