---
- name: update cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
- name: install dev tools
  apt: name={{item}} state=present
  with_items:
    - vim
    - tmux
    - curl
    - wget
    - git
    - fish
    - make
