---
- hosts: all
  become: true
  tasks:
  - name: "Build hosts file"
    blockinfile:
      dest: /etc/hosts
      content: "{{ lookup('template', 'hosts.template') }}"
      state: present
  - name: update hostname
    copy:
      dest: /etc/hostname
      content: "{{ inventory_hostname }}\n"
