---
- hosts: pi-cluster
  become: true
  tasks:
  - name: update cache
    apt:
      update_cache: yes
      cache_valid_time: 3600
  - name: install packages
    apt: name={{item}} state=present
    with_items:
      - redir
      - lxc
      - vagrant
      - vagrant-lxc
  - name: set lxc-net config
    copy:
      dest: /etc/default/lxc-net
      content: |
        USE_LXC_BRIDGE="true"
  - name: set lxc config
    copy:
      dest: /etc/lxc/default.conf
      content: |
        lxc.network.type = veth
        lxc.network.link = lxcbr0
        lxc.network.flags = up
        lxc.network.hwaddr = 00:16:3e:xx:xx:xx
  #- name: stop docker
    #service:
      #name: docker
      #enabled: no
      #state: stopped
  - name: Restart lxc-net
    service:
      name: lxc-net
      state: restarted
