---
- hosts: debian
  become: true

  tasks:
  - name: update cache
    apt:
      update_cache: yes
      cache_valid_time: 3600
  - name: install dev tools
    apt: name={{item}} state=present
    with_items:
      - vim
      - tmux
      - curl
      - wget
      - git
      - fish
      - make
      - locales # needed for tmux
# TODO
# dpkg-reconfigure locales
# 152 en us utf8
