---
- name: install telegraf on 64-bit
  apt:
    deb: https://dl.influxdata.com/telegraf/releases/telegraf_1.6.3-1_amd64.deb
- name: Build config
  copy:
    dest: /etc/telegraf/telegraf.conf
    content: "{{ lookup('template', 'telegraf.template.conf') }}"
- name: enable service
  systemd:
    name: telegraf
    enabled: yes
- name: Make sure a service is running
  systemd:
      state: restarted
      daemon_reload: yes
      name: telegraf
